
// DO NOT EDIT.

// DO NOT EDIT. This file is generated by the Surface framework.
// This file SHOULD be checked into source version control.

// This file is automatically updated during development when running `dev.js`.

import * as $0 from "./views/Die.js";
import * as $1 from "./views/Popup.js";
import * as $2 from "./views/ScoreButton.js";

const manifest = {
  views: {
    "./views/Die.js": $0,
    "./views/Popup.js": $1,
    "./views/ScoreButton.js": $2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
